package gobioinfo

import (
	"bytes"
	"fmt"
	"testing"
)

func TestSGAlign(t *testing.T) {

	fmt.Println("testing SGAlign...")

	rawTestData := bytes.NewBufferString(`@HWI-ST560:155:C574EACXX:3:1101:2214:1998 1:N:0:
AGCAGGGAGGACGATGCGGAACTGATGTCTAAGTACGCACGGCCGGTACAGTGAAACTGCGAATGGCTCGTGTCAGTCACTTCCAGCGGGCGTATGCCGT
+
CCCFFFFFHHHHHJJJJJJJJJJJJJJJJIIGHEIIJIGIGGIGFFCCDDECCDDDDDDDDDDDDCDCC-9?28A@>4@AAC3>4439B###########
@HWI-ST560:155:C574EACXX:3:1101:2300:1939 1:N:0:
CACAGGGAGGACGATGCGGGAGTGAGACCGTCTTGCTTACTTGTCCGATGAAATGAATGAAATAGAAAGTGGGAAAATAATGTGTCAGTCACTTCCAGCG
+
BBCFFFFFHHHHHJJJJJJJIJHIGIHHIJJJJJIGIIEHIIGHHHHFFFCEDDEDCCCDDDACDCDDD@CDDACBCCCDDCDEDDCDCCCCCDCC:@99
@HWI-ST560:155:C574EACXX:3:1101:2409:1942 1:N:0:
CACAGGGAGGACGATGCGGAAAAGAATGTGAATCATGGTGTTCTTGTGGTTGGCTATGGGACTCTTGATGGCAAAGATTACTGGCTTGTGAAAAAAGGGT
+
BBBFFFFFHHHHHFIJIJJJJJJJJIHIFIJJJJJJJJ=FGIJJJJHIJJJJHHHHFFFFFDEEEEDDDDDDDDDDDDDDDDDDDDD5?CCDCDD#####
@HWI-ST560:155:C574EACXX:3:1101:2433:1960 1:N:0:
AGCAGGGAGGACGATGCGGACAAGTCCCTGAGGAGCCCTTTGAGCCTGGTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAA
+
BCCFFFFFHHHHHJJJJJJJIJJJGJIJJJIJJJJJJJJJJGJIJIJHHHGFFFFFFEEEEEEEDDDBDDDDDDDCDDDDDDDDDDDDDDDDDDD@B@DB
@HWI-ST560:155:C574EACXX:3:1101:2381:1976 1:N:0:
AGCAGGGAGGACGATGCGGTGATGTTCACAGTGGCTAAGTTCCGCGGTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAAA
+
BCCFFFFFHHHHHIJJJJJJJJJIIHIIJJJFHJJJJJJJJJJJJJJHHFFFFFFEEEEEEEDDDDDDDDDDCDDBBBDDDDDDDDCDDDDDDD9BB>BD
@HWI-ST560:155:C574EACXX:3:1101:2403:1977 1:N:0:
GCTAGGGAGGACGATGCGGCTAAGTGGTTGGAACCCGATTGCCTCTCTGGAGCGTGTCAGTCACTTCCAGCGGGTGTCAGTCACTTCCAGCGGTCGTATG
+
@@@FFFFFHHGHHJJJJJJGIEFHFHGDHGIEGGHIIJIICHHIJHEFHGDDDCDD@BCCDDDDDDA@CDDDDD@><ACDDCCCCCC>CC?>B9@B>833
@HWI-ST560:155:C574EACXX:3:1101:4452:1943 1:N:0:
CACAGGGAGGACGATGCGGAGGAGAAGACCACATATGTGAAGGCCCCTGGTTGACTGGTTGTGGGCTCAGCTGACCAGCTGGGCTTGCCTGCTGCAGGCG
+
BBBFFFFFHHHHHJJJJJJJIJGGIJFBGH@GGHIGGDHIICHIJJHHHGFFFCDEEDCED@@@DDDDDDCCACDD@BBCCDDBCDDDDDDDDCA99<9@
@another test
AGCAGGGAGGACGATGCGGTTGTGATATAATACAACCTGCTAA
+
B@CDFFFFHHDDFHHIJJJIIIDGHBFGFHIGHGHG@EGHJHH
`)

	//rawTestData := bytes.NewBufferString("@HWI-ST560:155:C574EACXX:3:1101:2403:1977 1:N:0:\nGCTAGGGAGGACGATGCGGCTAAGTGGTTGGAACCCGATTGCCTCTCTGGAGCGTGTCAGTCACTTCCAGCGGGTGTCAGTCACTTCCAGCGGTCGTATG\n+\n@@@FFFFFHHGHHJJJJJJGIEFHFHGDHGIEGGHIIJIICHHIJHEFHGDDDCDD@BCCDDDDDDA@CDDDDD@><ACDDCCCCCC>CC?>B9@B>833\n")
	//																									                                                             GTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTG
	scanner := NewFASTQScanner(rawTestData)

	var testReads []FASTQRead
	for {
		newRead, err := scanner.NextRead()
		if err != nil {
			if err.Error() == "EOF" {
				break
			}
		}
		//	fmt.Println(newRead.DNASequence.Sequence)
		testReads = append(testReads, newRead)
	}
	subject := NewDNASequence("GTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTG")

	type testGroup struct {
		alignment          PWAlignment
		read               FASTQRead
		expectedCIGAR      string
		expectedQueryStart int
	}

	var testSuite []testGroup

	expectedCIGARS := []string{
		"mmmmmmmmmmmmmmmmmmmmxmmmmmmmmmm",
		"mmmmmmmmmmmmmmmmmmm",
		"mm",
		"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
		"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
		"mmmmmmmmmmmmmmmmmmmmmmmmmmm",
		"immmxxmjmmmjmmjxmmmmmjmmxmimimmimiimmxmmmmxxm",
		"",
	}

	for i, elem := range testReads {
		testSuite = append(testSuite, testGroup{

			// NB: there might be more than alignment returned by SG3pAlign()
			alignment:          elem.Sequence.SG3pAlign(subject.Sequence)[0],
			read:               elem,
			expectedCIGAR:      expectedCIGARS[i],
			expectedQueryStart: 69,
		})
	}

	for _, elem := range testSuite {
		fmt.Println(elem.alignment)
		if elem.expectedCIGAR != elem.alignment.ExpandedCIGAR {
			t.Error(
				"expected: \t",
				elem.expectedCIGAR,
				"\nbut got: \t\t",
				elem.alignment.ExpandedCIGAR,
				"\n",
			)
		}
	}
}

// func alignmentRepr(alignment PairWiseAlignment) PairWiseAlignment {}
